### ISSUE TITLE
Failed to execute script leaguephd (Patch 12.22)

### ISSUE THREAD

**Issue by seanaujong** [leaguephd/leaguephd-app#3]
![Capture](https://user-images.githubusercontent.com/52766813/204156953-aa050deb-a685-4109-b963-2400ddef4e83.PNG)

League PhD crashes when opening LoL client.

**Comment by jgw13323** [comment]
저도 마찬가지입니다

**Comment by jgw13323** [comment]
Me Too.

**Comment by ManuOverWeight** [comment]
What can we do? Is crashing for me too.

**Comment by Ye11owFlash** [comment]
same here
![Capture d’écran 2023-01-18 151232](https://user-images.githubusercontent.com/123020968/213284831-517e3b29-1b00-4b95-82eb-1a486133df2a.png)

**Comment by junepaykim** [comment]
Same here. I think it happens on Windows 11

**Comment by korry2** [comment]
same here. Please someone solve this :(

**Comment by leaguephd** [comment]
This was due to the incompatibility of lcu-driver with a change in the League Client API. Fixed by using the latest version of lcu-driver.

**Comment by korry2** [comment]
Oh many thanks sir. I was waiting for this 😊

23 May 2023 Sal 07:27 tarihinde League PhD ***@***.***> şunu
yazdı:
